from typing import Any

import marshmallow
from aiosnow.models._schema.helpers.pluck import Pluck as Pluck


class BaseField(marshmallow.fields.Field):
    pluck: Any = ...
    is_primary: Any = ...
    allow_none: bool = ...
    missing: Any = ...

    def __init__(self, *args: Any, pluck: Pluck = ..., is_primary: bool = ..., **kwargs: Any) -> None: ...
