from typing import Any

from aiosnow.models import TableModel as TableModel


class JournalModelSchema:
    sys_id: Any = ...
    sys_created_on: Any = ...
    sys_created_by: Any = ...
    element: Any = ...
    element_id: Any = ...
    name: Any = ...
    value: Any = ...
    sys_tags: Any = ...


class JournalModel(TableModel, JournalModelSchema): ...
