import json
from typing import (
    Any,
    Dict,
)

from marshmallow import Schema


class ConfigEncoder(json.JSONEncoder):
    def default(self, o: BaseConfigSchema.ConfigSegment) -> Dict[str, Any]: ...


class BaseConfigSchema(Schema):
    class ConfigSegment:
        def as_dict(self) -> Dict[str, Any]: ...

        def __init__(self, **config: Dict[str, Any]) -> None: ...

    def make_object(self, data: Dict[str, Any], **_: Any) -> Any: ...


class ClientConfig(BaseConfigSchema):
    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    basic_auth: Any = ...
    oauth: Any = ...
    use_ssl: Any = ...
    verify_ssl: Any = ...

    def make_object(self, data: Dict[str, Any], **_: Any) -> Any: ...


class ConfigSchema(BaseConfigSchema):
    address: Any = ...
    session: ClientConfig = ...

    def __init__(self, *args: Any, **kwargs: Any) -> None: ...

    def load(self, *args: Any, **kwargs: Any) -> ConfigSchema: ...
