from typing import Any


class AiosnowException(Exception): ...


class ConfigurationError(AiosnowException): ...


class AmbiguousClientAuthentication(AiosnowException): ...


class MissingClientAuthentication(AiosnowException): ...


class UnexpectedContentType(AiosnowException): ...


class ClientConnectionError(AiosnowException): ...


class SerializationError(AiosnowException): ...


class DeserializationError(AiosnowException): ...


class RequestError(AiosnowException):
    message: Any = ...
    status: Any = ...

    def __init__(self, message: str, status: int) -> None: ...


class ErrorResponse(RequestError): ...


class UnexpectedResponseContent(RequestError): ...


class UnexpectedPayloadType(AiosnowException): ...


class PayloadValidationError(AiosnowException): ...


class IncompatiblePayloadField(AiosnowException): ...


class UnknownPayloadField(AiosnowException): ...


class UnexpectedValue(AiosnowException): ...


class SchemaError(AiosnowException): ...


class SelectError(AiosnowException): ...


class InvalidContentMethod(AiosnowException): ...


class InvalidFieldName(AiosnowException): ...


class TooManyItems(AiosnowException): ...


class NoItems(AiosnowException): ...


class DeleteError(AiosnowException): ...
