from typing import Any


class AttachmentModelSchema:
    sys_id: Any = ...
    table_name: Any = ...
    file_name: Any = ...
    size_bytes: Any = ...
    sys_mod_count: Any = ...
    average_image_color: Any = ...
    image_width: Any = ...
    sys_updated_on: Any = ...
    sys_tags: Any = ...
    image_height: Any = ...
    sys_updated_by: Any = ...
    download_link: Any = ...
    content_type: Any = ...
    sys_created_on: Any = ...
    size_compressed: Any = ...
    compressed: Any = ...
    state: Any = ...
    table_sys_id: Any = ...
    chunk_size_bytes: Any = ...
    hash: Any = ...
    sys_created_by: Any = ...
