class BaseOperator:
    EQUALS: str = ...
    NOT_EQUALS: str = ...
    LESS: str = ...
    LESS_EQUALS: str = ...
    GREATER: str = ...
    GREATER_EQUALS: str = ...
    CONTAINS: str = ...
    NOT_CONTAINS: str = ...
    EMPTY: str = ...
    POPULATED: str = ...
    BETWEEN: str = ...
    ANYTHING: str = ...
    SAME: str = ...
    DIFFERENT: str = ...
    ONEOF: str = ...
    NOT_ONEOF: str = ...


class StringOperator(BaseOperator):
    EMPTYSTRING: str = ...
    STARTSWITH: str = ...
    ENDSWITH: str = ...


class ReferenceField(StringOperator): ...


class IntegerOperator(BaseOperator):
    class Related:
        GREATER: str = ...
        LESS: str = ...
        GREATER_EQUALS: str = ...
        LESS_EQUALS: str = ...


class DateTimeOperator(BaseOperator):
    ON: str = ...
    NOT_ON: str = ...
    TREND: str = ...
    RELATIVE_GREATER: str = ...
    RELATIVE_LESS: str = ...
    RELATIVE_EQUALS: str = ...
    RELATED_GREATER: str = ...
    RELATED_LESS: str = ...


class BooleanOperator(BaseOperator): ...


class EmailOperator:
    CHANGES: str = ...
    CHANGES_FROM: str = ...
    CHANGES_TO: str = ...


class LogicalOperator:
    AND: str = ...
    OR: str = ...
    NQ: str = ...
