from typing import Any

from marshmallow import Schema


class ErrorSchema(Schema):
    message: Any = ...
    detail: Any = ...


class ContentSchema(Schema):
    error: Any = ...
    result: Any = ...
    status: Any = ...
