from typing import (
    Any,
    List,
)

from aiosnow.query.condition import Condition as Condition


class BaseQueryable:
    name: Any = ...

    def __eq__(self, other: Any) -> Any: ...

    def __ne__(self, other: Any) -> Any: ...

    def __lt__(self, other: Any) -> Condition: ...

    def __le__(self, other: Any) -> Condition: ...

    def __gt__(self, other: Any) -> Condition: ...

    def __ge__(self, other: Any) -> Condition: ...

    def equals(self, other: Any) -> Condition: ...

    def not_equals(self, other: Any) -> Condition: ...

    def less_than(self, other: Any) -> Condition: ...

    def less_or_equals(self, other: Any) -> Condition: ...

    def greater_than(self, other: Any) -> Condition: ...

    def greater_or_equals(self, other: Any) -> Condition: ...

    def in_list(self, values: List[Any]) -> Condition: ...

    def not_in_list(self, values: List[Any]) -> Condition: ...

    def is_empty(self) -> Condition: ...

    def is_populated(self) -> Condition: ...

    def is_anything(self) -> Condition: ...
