from aiosnow.query.condition import Condition as Condition

from .base import BaseQueryable as BaseQueryable


class DateTimeQueryable(BaseQueryable):
    def on(self, value: str) -> Condition: ...

    def not_on(self, value: str) -> Condition: ...

    def before(self, value: str) -> Condition: ...

    def after(self, value: str) -> Condition: ...

    def until(self, value: str) -> Condition: ...

    def as_of(self, value: str) -> Condition: ...

    def between(self, value1: str, value2: str) -> Condition: ...
