from aiosnow.query.condition import Condition as Condition

from .base import BaseQueryable as BaseQueryable


class StringQueryable(BaseQueryable):
    def equals(self, value: str) -> Condition: ...

    def not_equals(self, value: str) -> Condition: ...

    def starts_with(self, value: str) -> Condition: ...

    def ends_with(self, value: str) -> Condition: ...

    def contains(self, value: str) -> Condition: ...

    def not_contains(self, value: str) -> Condition: ...

    def less_or_equals(self, value: str) -> Condition: ...

    def greater_or_equals(self, value: str) -> Condition: ...

    def between(self, value1: str, value2: str) -> Condition: ...
